/* 
 * File:   mcal_interrupt_gen_cfg.h
 * Author: Ahmed Mohamed
 *
 * Created on 11 dec 2023, 04:32 ?
 */

#ifndef MCAL_INTERRUPT_GEN_CFG_H
#define	MCAL_INTERRUPT_GEN_CFG_H

#define INTERRUPT_FEATURE_ENABLE  1U 
#define INTERRUPT_FEATURE_DISABLE 0U

#define INTERRUPT_PRIORITY_LEVELS_ENABLE      INTERRUPT_FEATURE_DISABLE
#define EXTERNAL_INTERRUPT_INTX_ENABLE        INTERRUPT_FEATURE_ENABLE
#define EXTERNAL_INTERRUPT_ONCHANGE_ENABLE    INTERRUPT_FEATURE_ENABLE

#define ADC_INTERRUPT_FEATURE_ENABLE 1U
#define ADC_INTERRUPT_FEATURE_DISABE 0U

#define ADC_INTERRUPT_STATUS   ADC_INTERRUPT_FEATURE_ENABLE

#define TIMER0_INTERRUPT_STATUS INTERRUPT_FEATURE_ENABLE
#endif	 /* MCAL_INTERRUPT_GEN_CFG_H */

